### ISSUE TITLE
Acceptance Specifications translations support

### ISSUE THREAD

**Issue by giflw** [sebastianbenz/Jnario#166]
Hi, 

I wish to know how to use translations in Acceptance Specifications, like example below, if there is a way. If not, there is someway to accomplish this or a planned feature?
- Original (English):

```
Feature: Searching for web pages via Google
  Scenario: Searching for Jnario
   Given I opened "http://www.google.com"
   When I search for "Jnario"
   Then the result should contain "Jnario - Executable Specifications for Java"
```
- Translated (e.g. Portuguese):

```
Funcionalidade: Pesquisando por páginas web via Google
  Cenário: Pesquisando por Jnario
   Dado que eu abri "http://www.google.com"
   Quando eu pesquiso por "Jnario"
   Então o resultado deveria conter"Jnario - Executable Specifications for Java"
```

Thanks

**Comment by sebastianbenz** [comment]
We already discussed this, but it is a hard problem to solve technically
and it is not planned in the near future.

**Comment by giflw** [comment]
I don't know xtext, but is there a way to set some tokens to be read from a external file?

**Comment by giflw** [comment]
Or maybe in a configurator class or annotation?

**Comment by sebastianbenz** [comment]
The tokens are compiled into a java lexer - they can't be simply replaced.

**Comment by giflw** [comment]
One last thought:
If the DSL have something like `translate "Feature" as "Funcionalidade"`, and in the definition of the DSL the Token FEATURE have a default value of "Feature", but behave as a variable, this could be accomplished, theoretically. But I don't know if this is feasible using Xtext.
