### ISSUE TITLE
Update site is down

### ISSUE THREAD

**Issue by Guite** [sebastianbenz/Jnario#167]
http://jnario.org/updates/releases/ throws a 404 error.
I've tried to switch to snapshots, but this requires more dependencies (jdt runners).
Is it possible to make the releases site available again?

**Comment by sebastianbenz** [comment]
It should still be working if you point your eclipse to it.

**Comment by Guite** [comment]
Thanks, will investigate. Maybe only the CI server has some kind of connection problem.

**Comment by Guite** [comment]
Works fine again :smile:
